trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerHubUsername: YOUR_DOCKER_USERNAME

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'

# Build Java Service
- script: |
    cd product-service-java
    mvn clean package
  displayName: 'Build Java Service'

# Build Python Service
- script: |
    cd order-service-python
    pip install -r requirements.txt
  displayName: 'Prepare Python Service'

# Build Frontend
- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build Frontend'

# Build Docker Images
- script: |
    docker build -t $(dockerHubUsername)/product-service:v1 ./product-service-java
    docker build -t $(dockerHubUsername)/order-service:v1 ./order-service-python
    docker build -t $(dockerHubUsername)/frontend-service:v1 ./frontend
  displayName: 'Build Docker Images'