apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service

        image: kellykyabega/product-service:v2

        ports:
        - containerPort: 8080

        env:
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: PRODUCT_SERVICE_URL


      
   
